services:
  app:
    build:
      context: app
      dockerfile: Dockerfile-dev
    ports:
      - 5000:8800
    volumes:
      - /app/bin
      - /app/obj
      - ./app:/app
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:8800"
  db:
    image: mcr.microsoft.com/azure-sql-edge:1.0.4
    environment:
      ACCEPT_EULA: 1
